services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  appclear:
    image: guiparpineli/clearapp
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - '/logs:/logs'
