## DO properties
do:
  spaces:
    key: Z3iKX2vl8VI5fshIHj4C/BCUyoVst8Stjaf6mvnd9AY
    secret: ${DO_SPACE_SECRET}
    endpoint: https://clearcontbucket.sfo3.digitaloceanspaces.com
    region: sfo3
    bucket: clearcontbucket

spring:
  datasource:
    url: jdbc:mysql://clearcontwebapp-mysql-1:3306/mydatabase
    username: root
    password: verysecret
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
vaadin:
  whitelisted-packages: com.vaadin, org.vaadin, com.storedobject
jwt:
  auth:
    secret: J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc=
server:
  servlet:
    session:
      tracking-modes: cookie
version: 0.3.0
logging:
  file:
    path: /home/logsJava
