## DO properties
do:
  spaces:
    key: DO009YTULPQF8ZYF68MX
    secret: Z3iKX2vl8VI5fshIHj4C/BCUyoVst8Stjaf6mvnd9AY
    endpoint: sfo3.digitaloceanspaces.com
    region: US
    bucket: clearcontbucket

spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: verysecret
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
vaadin:
  whitelisted-packages: com.vaadin, org.vaadin, com.storedobject
jwt:
  auth:
    secret: J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc=
server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  file:
    path: /logs

version: 0.9.12
