## DO properties
do:
  spaces:
    key: DO009YTULPQF8ZYF68MX
    secret: Z3iKX2vl8VI5fshIHj4C/BCUyoVst8Stjaf6mvnd9AY
    endpoint: sfo3.digitaloceanspaces.com
    region: US
    bucket: clearcontbucket

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: verysecret
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
vaadin:
  whitelisted-packages: com.vaadin, org.vaadin, com.storedobject
jwt:
  auth:
    secret: J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc=
server:
  servlet:
    session:
      tracking-modes: cookie

logging:
  file:
    path: ./logsJava

version: 0.3.0