## DO properties
do:
  spaces:
#    key: DO009YTULPQF8ZYF68MX
#    secret: Z3iKX2vl8VI5fshIHj4C/BCUyoVst8Stjaf6mvnd9AY
    endpoint: s3://arn:aws:s3:us-east-2:010526270156:accesspoint/clearcont
    region: us-east-2
    bucket: clearcont

spring:
#  flyway:
#    baseline-on-migrate: true
#    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://database-1.cv0oickea9zv.us-east-2.rds.amazonaws.com/clearcont_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: hXTLt2DZ8fdjcBg
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
jwt:
  auth:
    secret: J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc=
server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  file:
    path: /logs

version: 0.9.9
